<!DOCTYPE html>
<html lang="en">
<head>
    <title>Sawazon</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Sawazon webpage">
    <meta name="author" content="Filip Hrenić, filip.hrenic@sofascore.com">

    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
    <link rel="icon" href="favicon.ico" type="image/x-icon">

    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="/web/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css"/>
    <link href="/web/css/bootstrap-select.min.css" media="all" rel="stylesheet" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="/web/js/plugins/canvas-to-blob.min.js" type="text/javascript"></script>
    <script src="/web/js/fileinput.min.js"></script>
    <script src="/web/js/bootstrap-select.min.js"></script>
    <script src="/web/js/jqBootstrapValidation.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="/web/css/sawazon.css">
    <script src="/web/js/sawazon.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

{navbar->toHtml}
<h1>navbar for normal user -> login and register</h1>
((session))
</body>
</html>