<!DOCTYPE html>
<html lang="en">
<head>
    <title>Sawazon</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Sawazon webpage">
    <meta name="author" content="Filip Hrenić, filip.hrenic@sofascore.com">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">

    <link href="/web/css/bootstrap.min.css" rel="stylesheet">
    <link href="/web/css/fileinput.min.css" media="all" rel="stylesheet" type="text/css"/>
    <link href="/web/css/bootstrap-select.min.css" media="all" rel="stylesheet" type="text/css"/>
    <link href="/web/css/bootstrap-multiselect.css" media="all" rel="stylesheet" type="text/css"/>
    <link href="/web/css/sawazon.css" media="all" rel="stylesheet" type="text/css"/>
</head>
<body style="background-color: ((bg_color))">

<header>
    {navbar->toHtml}
</header>
{content->toHtml}

<!-- Footer -->
<hr>
<footer>
    <div class="rowcenter-block container-fluid" style="max-width: 75%">
        <div class="col-lg-12">
            <p>Copyright &copy; Sawazon 2016</p>
        </div>
    </div>
    <!-- /.row -->
</footer>

<script src="/web/js/jquery-2.1.3.min.js"></script>
<script src="/web/js/bootstrap.min.js"></script>
<script src="/web/js/bootstrap-multiselect.js"></script>
<script src="/web/js/bootstrap-multiselect-collapsible-groups.js"></script>
<script src="/web/js/plugins/canvas-to-blob.min.js" type="text/javascript"></script>
<script src="/web/js/fileinput.min.js"></script>
<script src="/web/js/bootstrap-select.min.js"></script>
<script src="/web/js/bootstrap-rating.js"></script>
<script src="/web/js/logreg.js"></script>

</body>
</html>