<!-- Page Content -->
<div class="container">

    <div class="row">
        <div class="col-md-3">
            <p class="lead">Administration</p>
        </div>
        <div class="col-md-9">
        </div>
    </div>

    <div class="row">
        <div class="col-md-3">
            <div class="list-group">
                <a href="#newCategory" class="list-group-item" role="tab" data-toggle="tab">
                    <icon class="fa fa-plus"></icon>
                    New Category
                </a>
                <a href="#users" class="list-group-item" role="tab" data-toggle="tab">
                    <i class="fa fa-user"></i> Users
                </a>
                <a href="#something" class="list-group-item" role="tab" data-toggle="tab">
                    <i class="fa fa-question"></i> Add more functionalities...
                </a>
            </div>
        </div>

        <div class="col-md-9">
            <!-- Tab panes -->
            <div class="tab-content">
                <div class="tab-pane fade active in" id="newCategory">
                    {category_form->toHtml}
                </div>
                <div class="tab-pane fade" id="users">
                    {users->toHtml}
                </div>
                <div class="tab-pane fade" id="something">
                    <h2>The end</h2>
                    <img src="http://www.weepop.net/wp-content/uploads/2015/02/thatsall.jpg"/>
                </div>
            </div>
        </div>
    </div>

</div>
<!-- /.container -->
