<div class="container">
    <div class="row">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">@{user:username}: Edit profile</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-5 col-lg-5 ">


                        <div align="center">
                            <img src="{usr_img}" class="img-circle img-responsive">
                        </div>
                        <div style="padding: 0px 10px 0px 10px">

                            <form class="form-horizontal" action="{apply_filer_link}" method="post">
                                <fieldset>
                                    <legend>Apply filters</legend>
                                    <div class="row">
                                        <div class="col-md-9">
                                            <div class="form-group">
                                                {filters}
                                            </div>
                                        </div>
                                        <div class="col-md-3">
                                            <div class="form-group has-feedback">
                                                <button class="btn btn-danger" type="submit">Apply</button>
                                            </div>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>

                        </div>

                        <hr>

                        <input name="upload_picture" type="file" accept="image/*"
                               class="file" multiple
                               data-show-upload="true"
                               data-upload-url="{picture_upload_link}"
                               data-drop-zone-enabled="true"
                               data-drop-zone-title="Drag & drop photo here"
                               data-allowed-file-extensions='["png", "jpg", "jpeg"]'
                               data-show-caption="true" id="picture_change">
                        <script>
                            $('#picture_change').on('fileuploaded', function (event, data, previewId, index) {
                                location.reload();
                            });
                        </script>

                    </div>

                    <div class=" col-md-6 col-lg-6 ">

                        <div>
                            <form id="edit_profile_form" class="form-horizontal" action="{edit_save_link}"
                                  method="post">

                                <fieldset>
                                    <input type="hidden" name="user_id" value="{user:user_id}">

                                    <label for="r_firstname">Basic info</label>
                                    <div class="form-group has-feedback">
                                        <input name="first_name" class="form-control" type="text"
                                               value="{user:first_name}" required>
                                    </div>

                                    <div class="form-group has-feedback">
                                        <input name="last_name" class="form-control" type="text"
                                               value="{user:last_name}" required>
                                    </div>

                                    <div class="form-group has-feedback">
                                        <span class="glyphicon glyphicon-calendar form-control-feedback"></span>
                                        <input name="date_of_birth" class="form-control"
                                               type="date" value="{user:date_of_birth}" required="">
                                    </div>

                                    <label for="r_email">Contact info</label>
                                    <div class="form-group has-feedback">
                                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                                        <input name="email" class="form-control" type="email"
                                               value="{user:email}" required>
                                    </div>

                                    <div class="form-group has-feedback">
                                        <span class="glyphicon glyphicon-earphone form-control-feedback"></span>
                                        <input name="telephone" class="form-control" type="tel"
                                               value="{user:telephone}" required>
                                    </div>

                                    <div class="form-group has-feedback">
                                        <span class="glyphicon glyphicon-home form-control-feedback"></span>
                                        <input name="street" class="form-control" type="text"
                                               value="{user:street}" required>
                                    </div>

                                    <div class="form-group has-feedback">
                                        <span class="glyphicon glyphicon-map-marker form-control-feedback"></span>
                                        <input name="city" class="form-control" type="text"
                                               value="{user:city}" required>
                                    </div>

                                    <div class="form-group has-feedback">
                                        <select name="country_id"
                                                class="selectpicker show-tick form-control"
                                                data-live-search="true"
                                                title="{country_name}" id="country_select">
                                            {country_opts}
                                        </select>
                                    </div>

                                    <div class="form-group has-feedback" align="center">
                                        <button class="btn btn-danger" type="submit">Save</button>
                                    </div>

                                </fieldset>

                            </form>
                        </div>

                        <hr>

                        <div align="center">

                            <label for="new_password">Change password</label>
                            <form class="form-horizontal" id="new_password" action="{change_pswd_link}" method="post">
                                <fieldset>
                                    <input type="hidden" name="user_id" value="{user:user_id}">

                                    <div class="form-group">
                                        <label class="col-md-4 control-label" for="old_password">Old password</label>
                                        <div class="col-md-6">
                                            <input id="old_password" name="old_password" type="password"
                                                   class="form-control input-md" required="">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-4 control-label" for="new_password">New password</label>
                                        <div class="col-md-6">
                                            <input id="new_password" name="new_password" type="password"
                                                   class="form-control input-md" required="">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <label class="col-md-4 control-label" for="new_password2">Repeat
                                            password</label>
                                        <div class="col-md-6">
                                            <input id="new_password2" name="new_password2" type="password"
                                                   class="form-control input-md" required="">
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-md-5"></div>
                                        <div class="col-md-6">
                                            <button class="btn btn-danger" type="submit" id="change_password">Change
                                            </button>
                                        </div>
                                    </div>

                                </fieldset>
                            </form>
                            <script>
//                                $('#new_password').submit(function () {
//                                    return $('#new_password').val() == $('#new_password2').val();
//                                });
                            </script>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>