<div class="container">
    <div class="row">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">@{user:username}
                    ?? edit_profile_link
                    :: <a href="{edit_profile_link}">
                        <span class="label label-danger">Edit profile</span>
                       </a>
                    || ??
                </h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4 col-lg-4 " align="center">
                        <img src="{user_image}" class="img-circle img-responsive">
                    </div>

                    <div class=" col-md-8 col-lg-8 ">
                        <table class="table table-user-information">
                            <tbody>
                            <tr>
                                <td>Name:</td>
                                <td>{user:first_name} {user:last_name}</td>
                            </tr>
                            <tr>
                                <td>Date of Birth</td>
                                <td>{user:date_of_birth}</td>
                            </tr>
                            <tr>
                                <td>Home Address</td>
                                <td>{user:city}, {country}</td>
                            </tr>
                            <tr>
                                <td>Email</td>
                                <td><a href="mailto:{user:email}">{user:email}</a></td>
                            </tr>
                            <tr>
                                <td>Phone Number</td>
                                <td>{user:telephone}</td>
                            </tr>
                            <tr>
                                <td>Sawazoninan since</td>
                                <td>{user:joined_date}</td>
                            </tr>
                            ?? can_follow
                            ::
                            <tr>
                                <td>
                                    <button class="btn btn-success" onclick="follow()">
                                        <i class="glyphicon glyphicon-ok"></i> Follow
                                    </button>
                                    <button class="btn btn-danger" onclick="unfollow()">
                                        <i class="glyphicon glyphicon-remove"></i> Unfollow
                                    </button>
                                </td>
                                <td></td>
                            </tr>
                            ||
                            ??
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="panel-footer">
                <h3>{user:username}'s posts</h3>
                <hr>
                {posts->toHtml}
                <hr>
                <h3>{user:username}'s products</h3>
                <hr>
                {products->toHtml}
            </div>
        </div>
    </div>
</div>

?? can_follow ::
<script>
    function follow() {
        follow_helper(
            '1',
            "You are already following {user:username}",
            "You are now following {user:username}",
            'add'
        );
    }

    function unfollow() {
        follow_helper(
            '0',
            "You are not following {user:username}",
            "You have unfollowed {user:username}",
            'delete'
        );
    }

    function follow_helper($wrong_data, $wrong_msg, $ok_msg, $action) {
        var $follower = "{user_id}";
        var $followee = "{user:user_id}";

        $.ajax({
            url: "{follow_check}",
            type: "POST",
            data: {
                follower: $follower,
                followee: $followee
            },
            success: function ($data) {
                if ($data == $wrong_data) {
                    alert($wrong_msg);
                } else {

                    $.ajax({
                        url: "{follow_modify}",
                        type: "POST",
                        data: {
                            follower: $follower,
                            followee: $followee,
                            action: $action
                        },
                        success: function ($data) {
                            alert($ok_msg);
                        }
                    });

                }
            }
        });
    }
</script>
|| ??