<div class="media">
    <div class="media-left">
        <a href="#">
            <img class="media-object img-rounded" src="((user-img))" width="64px" height="72px">
        </a>
    </div>
    <div class="media-body">
        <div class="row">
            <div class="col-lg-8">
                <h4 class="media-heading">
                    <strong>((username))</strong>
                    <small> added a product <a href="((plink))">((pname))</a> on ((date))</small>
                </h4>
                <p>((content))</p>
            </div>
        </div>
    </div>
</div>