<div class="media">
    <div class="media-left">
        <img class="media-object img-rounded" src="{user-img}" width="64px" height="72px">
    </div>
    <div class="media-body">
        <div class="row">
            <div class="col-lg-8">
                <h4 class="media-heading">
                    <strong><a href="{user_link}">{username}</a></strong>
                    <small> added a product <a href="{plink}">{pname}</a> on {date}</small>
                </h4>
                <h5><strong>{heading}</strong> --- {price}</h5>
                <p>{content}</p>
            </div>
        </div>
    </div>
</div>