<div class="container">
    <form id="product_upload_form" class="form-horizontal" action="{form_link}"
          method="post" enctype="multipart/form-data">
        <fieldset>


            <legend style="text-align: center">Add a new product</legend>

            <input type="hidden" name="user_id" value="{user_id}">

            <div class="form-group">
                <label class="col-md-4 control-label" for="category_id">Product category</label>
                <div class="col-md-4">
                    <select name="category_id" class="selectpicker show-tick form-control"
                            data-live-search="true" title="Category" required>
                        {categ_opts}
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="name">Product name</label>
                <div class="col-md-4">
                    <input name="name" type="text" placeholder="My Product" class="form-control input-md" required>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="description">Product description</label>
                <div class="col-md-4">
                    <textarea class="form-control" name="description" required></textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="price">Price</label>
                <div class="col-md-4">
                    <div class="input-group">
                        <input name="price" class="form-control" placeholder="12.50" type="text" required>
                        <span class="input-group-addon">{currency}</span>
                    </div>

                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="allow_review">Allow review</label>
                <div class="col-md-4">
                    <label class="radio-inline">
                        <input type="radio" name="allow_review" value="1" checked="checked">
                        Yes
                    </label>
                    <label class="radio-inline">
                        <input type="radio" name="allow_review" value="0">
                        No
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="product_picture">Product picture</label>
                <div class="col-md-4">
                    <input name="product_picture" type="file" class="file"
                           multiple accept="image/*"
                           data-show-upload="false"
                           data-allowed-file-extensions='["png", "jpg", "jpeg"]'
                           data-show-caption="true">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="upload-product"></label>
                <div class="col-md-4">
                    <button class="btn btn-danger" type="submit">Post it!</button>
                </div>
            </div>

        </fieldset>
    </form>
</div>
