<div class="container">
    <form class="form-horizontal">
        <fieldset>

            <!-- Form Name -->
            <legend style="text-align: center">Add a new product</legend>

            <!-- Select Basic -->
            <div class="form-group">
                <label class="col-md-4 control-label" for="category_id">Product category</label>
                <div class="col-md-4">
                    <select id="category_id" name="category_id" class="form-control">
                        [categ_opts]
                    </select>
                </div>
            </div>

            <!-- Text input-->
            <div class="form-group">
                <label class="col-md-4 control-label" for="name">Product name</label>
                <div class="col-md-4">
                    <input id="name" name="name" type="text" placeholder="Name" class="form-control input-md">

                </div>
            </div>

            <!-- Textarea -->
            <div class="form-group">
                <label class="col-md-4 control-label" for="description">Product description</label>
                <div class="col-md-4">
                    <textarea class="form-control" id="description" name="description">Description</textarea>
                </div>
            </div>

            <!-- Multiple Radios (inline) -->
            <div class="form-group">
                <label class="col-md-4 control-label" for="allow_review">Allow review</label>
                <div class="col-md-4">
                    <label class="radio-inline" for="allow_review-0">
                        <input type="radio" name="allow_review" id="allow_review-0" value="1" checked="checked">
                        Yes
                    </label>
                    <label class="radio-inline" for="allow_review-1">
                        <input type="radio" name="allow_review" id="allow_review-1" value="0">
                        No
                    </label>
                </div>
            </div>

            <!-- Button -->
            <div class="form-group">
                <label class="col-md-4 control-label" for="upload-product"></label>
                <div class="col-md-4">
                    <button id="upload-product" name="upload-product" class="btn btn-danger">Post it!</button>
                </div>
            </div>

        </fieldset>
    </form>
</div>
