<div class="container">
    <div class="thumbnail">
        <div class="row">
            <img class="col-xs-6 img-responsive" src="((img-link))"
                 style="height: auto; width: 50%; padding-top: 30px">
            <div class="col-xs-6" style="height: auto; width: 50%">
                {graph->toHtml}
            </div>
        </div>

        <div class="caption-full">
            <h4 class="pull-right">((price))</h4>
            <h2><strong>((name))</strong></h2>
            <p>((description))</p>
        </div>
        <div class="ratings">
            <p class="pull-right">((views))</p>
            <p>
                {rating->toHtml}
                ((number-reviews))
            </p>
        </div>
    </div>

    <div class="well">

        <div class="row">
            <div class="col-lg-12">
                <h3>Reviews for this product</h3>
            </div>
        </div>

        [reviews->toHtml]

        <hr>

        {reviews_footer->toHtml}

    </div>
</div>

