<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img class="img-thumbnail img-responsive" src="((img-link))">
<!--             style="max-width: 255px; min-width: 255px; max-height: 160px; min-height: 160px">-->
        <div class="caption">
            <h4 class="pull-right">((price))</h4>
            <h4>
                <a href="((link))">((heading))</a>
            </h4>
            <p>((description))</p>
        </div>
        <div class="ratings">
            <p class="pull-right">((reviews))</p>
            <p>
                {rating->toHtml}
            </p>
        </div>
    </div>
</div>