<div class="row">
    <div class="col-lg-12">
        <h1>Top viewed products
            <small>Check them out</small>
        </h1>
    </div>
</div>

<div id="prodcut_carousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        {items->getIndicator}
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        {items->toHtml}
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#prodcut_carousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#prodcut_carousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>