<hr>

<div class="media">
    <div class="media-left">
        <a href="#">
            <img class="media-object img-rounded" src="((user-img))" width="64px" height="72px">
        </a>
    </div>
    <div class="media-body">
        <div class="row">
            <div class="col-lg-8">
                <h4 class="media-heading">
                    <strong>((username))</strong>
                    <small> left a review on ((date))</small>
                    <small>{rating->toHtml}</small>
                </h4>
                <p>((content))</p>
            </div>

        </div>

    </div>
</div>

<!--<div class="row">-->
<!--    <div class="col-md-12">-->
<!--        <div class="container row">-->
<!--            <div class="col-lg-8">-->
<!--                <h4><b>((username))</b>-->
<!--                    <small>left a review on ((date))</small>-->
<!--                </h4>-->
<!--                <p>((content))</p>-->
<!--            </div>-->
<!--<div class="col-lg-4 pull-right">-->
<!--    {rating->toHtml}-->
<!--</div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->