<div class="container">
    <div class="row">

        <div class="col-md-3">
            <p class="lead">Pick a category</p>
            <div class="list-group">
                [category_items->toHtml]
            </div>
        </div>

        <div class="col-md-9">

            <div class="row carousel-holder">
                <div class="col-md-12">
                    <div><h1>PLACEHOLDER FOR GRAPH</h1></div>
                </div>
            </div>

            <div class="row">
                [items->toHtml]
            </div>

        </div>
    </div>
</div>