index:
  url:
  controller: index
  action: display

captcha:
  url: generate/captcha
  controller: generate/captcha
  action: display

image:
  url: image/<content>/<id>
  controller: generate/image
  action: display
  regexs:
    content: "[[:alpha:]]+"
    id: "\\d+"

content:
  url: content/<content>/<id>
  controller: content
  action: display
  regexs:
    content: "[[:alpha:]]+"
    id: "\\d+"

rss:
  url: feed/rss/<content>/<id>
  controller: generate/rss
  action: get
  regexs:
    content: "[[:alpha:]]+"
    id: "\\d+"

user_login:
  url: user/login
  controller: userControll
  action: login

user_register:
  url: user/register
  controller: userControll
  action: register