test:
  url: test
  controller: test
  action: test

###########
# visitor #
###########

index:
  url: ""
  controller: index
  action: display
  remember: true

content: # not used acctualy
  url: content/<content>/<id>
  controller: content
  action: display
  regexs:
    content: "[[:alpha:]]+"
    id: "\\d+"
  remember: true

error:
  url: error/<code>
  controller: info
  action: error
  regexs:
    code: "\\d+"

info:
  url: info/<about>
  controller: info
  action: about
  regexs:
    about: "[[:alpha:]]+"

image:
  url: image/<content>/<id>
  controller: generate/image
  action: display
  regexs:
    content: "[[:alpha:]]+"
    id: "\\d+"

rss:
  url: feed/rss/<content>/<id>
  controller: generate/rss
  action: get
  regexs:
    content: "[[:alpha:]]+"
    id: "\\d+"

captcha:
  url: generate/captcha
  controller: generate/captcha
  action: display

category_report:
  url: generate/json/category
  controller: generate/graph
  action: category_json

product_report:
  url: generate/json/product
  controller: generate/graph
  action: product_json

category_show:
  url: category/<id>
  controller: categoryControl
  action: display
  remember: true
  regexs:
    id: "\\d+"

product_show:
  url: product/<id>
  controller: productControl
  action: display
  remember: true
  regexs:
    id: "\\d+"

search:
  url: search
  controller: search
  action: show
  remember: true

user_login:
  url: user/login
  controller: userControl
  action: login

user_register:
  url: user/register
  controller: userControl
  action: register

username_check:
  url: user/check/username
  controller: userControl
  action: checkUsername

email_check:
  url: user/check/email
  controller: userControl
  action: checkEmail

user_show:
  url: user/<id>
  controller: userProfileControl
  action: show
  remember: true
  regexs:
    id: "\\d+"

all_tags:
  url: tag/all
  controller: search
  action: allTags

##########
#  user  #
##########

product_add:
  url: product/add
  controller: productControl
  action: showForm
  remember: true
  access: 1

product_save:
  url: product/save
  controller: productControl
  action: newProduct
  access: 1

post_save:
  url: post/save
  controller: postControl
  action: newPost
  access: 1

change_currency:
  url: user/change/currency
  controller: userControl
  action: changeCurrency
  access: 1

change_bgcolor:
  url: user/change/bgcolor
  controller: userControl
  action: changeBGColor
  access: 1

review_add:
  url: review/add
  controller: reviewControl
  action: addReview
  access: 1

user_logout:
  url: user/logout
  controller: userControl
  action: logout
  access: 1

follow_check:
  url: user/check/follows
  controller: userProfileControl
  action: checkFollows
  access: 1

follow_modify:
  url: user/follow
  controller: userProfileControl
  action: modifyFollow
  access: 1

edit_profile_show:
  url: user/edit/<id>
  controller: userProfileControl
  action: editShow
  remember: true
  regexs:
    id: "\\d+"
  access: 1

edit_profile_save:
  url: user/edit/save
  controller: userProfileControl
  action: editSave
  access: 1

###########
#  admin  #
###########

category_add:
  url: category/add
  controller: categoryControl
  action: addCategory
  access: 3

admin:
  url: admin
  controller: admin
  action: display
  remember: true
  access: 3

all_usernames:
  url: user/usernames
  controller: userControl
  action: allUsernames
  access: 3

users_action:
  url: user/action
  controller: userControl
  action: applyAction
  access: 3
