<hr>

<div class="media">
    <div class="media-left">
        <img class="media-object img-rounded" src="{user-img}" width="64px" height="72px">
    </div>
    <div class="media-body">
        <div class="row">
            <div class="col-lg-8">
                <h4 class="media-heading">
                    <strong><a href="{user_link}">{username}</a></strong>
                    <small> left a review on {date}</small>
                    <small>{rating->toHtml}</small>
                </h4>
                <p>{content}</p>
            </div>

        </div>

    </div>
</div>