<div class="media">
    <div class="media-left">
        <a href="#">
            <img class="media-object img-rounded" src="{user-img}" width="64px" height="72px">
        </a>
    </div>
    <div class="media-body">
        <div class="row">
            <div class="col-lg-8">
                <h4 class="media-heading">
                    <strong>{username}</strong>
                    <small> posted on {date}</small>
                </h4>
                <h5><strong>{heading}</strong></h5>
                <p>{content}</p>
            </div>
        </div>
    </div>
</div>