<form class="form-horizontal">
    <fieldset>
        <legend>New post</legend>

        <div class="form-group">
            <label class="col-md-4 control-label" for="heading"></label>
            <div class="col-md-4">
                <input id="heading" name="heading" type="text" placeholder="Heading" class="form-control input-md"
                       required="">
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="content"></label>
            <div class="col-md-4">
                <textarea class="form-control" id="content" name="content">Write #something</textarea>
            </div>
        </div>

        <div class="form-group">
            <label class="col-md-4 control-label" for="xxxx"></label>
            <div class="col-md-4">
                <button id="xxxx" name="xxxx" class="btn btn-danger">Publish</button>
            </div>
        </div>

    </fieldset>
</form>