<div class="media">
    <div class="media-left">
        <img class="media-object img-rounded" src="{usr-img}" width="64px" height="72px">
    </div>

    <div class="row media-body new_post_form">
        <form action="{form-link}" method="post">
            <input type="hidden" name="user_id" value="{user_id}">
            <input class="form-control" name="heading" type="text"
                   placeholder="Heading" required style="width: 25%;">
            <textarea class="form-control" name="content" style="width: 70%;">Write #something</textarea>
            <button type="submit" class="btn btn-danger">Publish</button>
        </form>
    </div>
</div>

<hr>