<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            {left->toHtml}
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            {search->toHtml}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#" data-toggle="modal" data-target="#login-modal" onclick="logregShowHide(true)"><span
                            class="glyphicon glyphicon-user"></span> Login</a></li>
                <li><a data-toggle="modal" data-target="#login-modal" onclick="logregShowHide(false)"><span
                            class="glyphicon glyphicon-share"></span> Register</a></li>

                <script>
                    function logregShowHide($isLogin) {
                        var $login = $('#login-form');
                        var $register = $('#register-form');
                        var $active, $disabled;

                        if ($isLogin) {
                            $active = $login;
                            $disabled = $register;
                        } else {
                            $active = $register;
                            $disabled = $login;
                        }

                        $active.css("display", "block");
                        $disabled.css("display", "none");
                    }
                </script>
            </ul>
        </div>
    </div>
</nav>
{logreg->toHtml}
