<div>
    <form class="nav navbar-left navbar-form" role="search"
          action="{search_link}" method="post" id="tag-search-form">
        <div class="form-group has-feedback">
            <span class="glyphicon glyphicon-search form-control-feedback"></span>
            <input name="search" type="text" class="form-control"
                   placeholder="#tag" required id="search-tag-box">
        </div>
        <button type="submit" class="btn btn-danger">Search</button>
    </form>
</div>

<script>
    $("#tag-search-form").submit(function () {
        return $("#search-tag-box").val().length != 0;
    });

    $.ajax({
        url: "{tags_link}",
        success: function ($tags) {
            $('#search-tag-box').tokenfield({
                autocomplete: {
                    source: $tags,
                    delay: 100
                },
                showAutocompleteOnFocus: true
            });
        }
    });
</script>