<div >
    <form class="form-horizontal" action="{form_link}"
          method="post" enctype="multipart/form-data">
        <fieldset>
            <!-- Form Name -->

            <div class="form-group">
                <label class="col-md-4 control-label" for="name">Name</label>
                <div class="col-md-4">
                    <input id="name" name="name" type="text" placeholder="My category" class="form-control input-md"
                           required="">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="description">Description</label>
                <div class="col-md-4">
                <textarea class="form-control" id="description"
                          name="description">Write a short description...</textarea>
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="category_picture">Category picture</label>
                <div class="col-md-4">
                    <input name="category_picture" type="file" class="file"
                           multiple accept="image/*"
                           data-show-upload="false"
                           data-allowed-file-extensions='["png", "jpg", "jpeg"]'
                           data-show-caption="true">
                </div>
            </div>

            <div class="form-group">
                <label class="col-md-4 control-label" for="upload-category"></label>
                <div class="col-md-4">
                    <button class="btn btn-danger" type="submit">Create</button>
                </div>
            </div>

        </fieldset>
    </form>
</div>
