<div class="row">
    <div class="col-xs-6">
        <label for="products-cheap">Cheapest products</label>
        <div id="products-cheap" style="height: auto; width: 100%"></div>
    </div>

    <div class="col-xs-6">
        <label for="products-expensive">Most expensive products</label>
        <div id="products-expensive" style="height: auto; width: 100%;"></div>
    </div>
</div>

<script>
    $.ajax({
        url: "((graph-link))",
        method: "POST",
        data: {
            category_id: ((category_id))
        },
//        dataType: json,
// don't know why it doesn't work with this because I set heading to application/json

        success: function ($data) {

            // expensive
            new Morris.Bar({
                element: 'products-expensive',
                data: $data['expensive'],
                xkey: 'name',
                ykeys: ['price'],
                labels: ['Price']
            });

            // cheap
            new Morris.Bar({
                element: 'products-cheap',
                data: $data['cheap'],
                xkey: 'name',
                ykeys: ['price'],
                labels: ['Price']
            });

        }
    });
</script>