<div class="container" >
    <div class="thumbnail">
        <img class="img-responsive" src="((img-link))" width="800px" height="300px">
        <div class="caption-full">
            <h4 class="pull-right">((price))</h4>
            <h2><strong>((name))</strong></h2>
            <p>((description))</p>
        </div>
        <div class="ratings">
            <p class="pull-right">((number-reviews))</p>
            <p>
                {rating->toHtml}
                ((stars))
            </p>
        </div>
    </div>

    <div class="well">

        <div class="row">
            <div class="col-lg-12">
                <h3>Reviews for this product</h3>
            </div>
        </div>

        [reviews->toHtml]

        <hr>

        <div class="container">
            <h3>form za unos novog ako je logiran</h3>
        </div>

    </div>
</div>

