<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="((img-link))" height="320px" width="150px">
        <div class="caption">
            <h4 class="pull-right">((price))</h4>
            <h4>
                <a href="((link))">((heading))</a>
            </h4>
            <p>((description))</p>
        </div>
        <div class="ratings">
            <p class="pull-right">((review-number)) reviews</p>
            <p>
                {rating->toHtml}
            </p>
        </div>
    </div>
</div>